export default {
  type: 'Program',
  start: 0,
  end: 527,
  body: [
    {
      type: 'ImportDeclaration',
      start: 0,
      end: 47,
      specifiers: [
        {
          type: 'ImportDefaultSpecifier',
          start: 7,
          end: 8,
          local: {
            type: 'Identifier',
            start: 7,
            end: 8,
            name: 'A',
          },
        },
        {
          type: 'ImportSpecifier',
          start: 12,
          end: 19,
          imported: {
            type: 'Identifier',
            start: 12,
            end: 19,
            name: 'Welcome',
          },
          local: {
            type: 'Identifier',
            start: 12,
            end: 19,
            name: 'Welcome',
          },
        },
      ],
      source: {
        type: 'Literal',
        start: 27,
        end: 46,
        value: '@atlaskit/welcome',
        raw: "'@atlaskit/welcome'",
      },
    },
    {
      type: 'FunctionDeclaration',
      start: 49,
      end: 235,
      id: {
        type: 'Identifier',
        start: 58,
        end: 61,
        name: 'App',
      },
      expression: false,
      generator: false,
      async: false,
      params: [],
      body: {
        type: 'BlockStatement',
        start: 64,
        end: 235,
        body: [
          {
            type: 'ReturnStatement',
            start: 68,
            end: 233,
            argument: {
              type: 'JSXElement',
              start: 81,
              end: 228,
              openingElement: {
                type: 'JSXOpeningElement',
                start: 81,
                end: 86,
                attributes: [],
                name: {
                  type: 'JSXIdentifier',
                  start: 82,
                  end: 85,
                  name: 'div',
                },
                selfClosing: false,
              },
              closingElement: {
                type: 'JSXClosingElement',
                start: 222,
                end: 228,
                name: {
                  type: 'JSXIdentifier',
                  start: 224,
                  end: 227,
                  name: 'div',
                },
              },
              children: [
                {
                  type: 'JSXText',
                  start: 86,
                  end: 93,
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 93,
                  end: 155,
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 93,
                    end: 155,
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 102,
                        end: 113,
                        name: {
                          type: 'JSXIdentifier',
                          start: 102,
                          end: 106,
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 107,
                          end: 113,
                          value: 'Sara',
                          raw: '"Sara"',
                        },
                      },
                      {
                        type: 'JSXAttribute',
                        start: 114,
                        end: 127,
                        name: {
                          type: 'JSXIdentifier',
                          start: 114,
                          end: 123,
                          name: 'otherName',
                        },
                        value: {
                          type: 'JSXExpressionContainer',
                          start: 124,
                          end: 127,
                          expression: {
                            type: 'Literal',
                            start: 125,
                            end: 126,
                            value: 2,
                            raw: '2',
                          },
                        },
                      },
                      {
                        type: 'JSXAttribute',
                        start: 128,
                        end: 143,
                        name: {
                          type: 'JSXIdentifier',
                          start: 128,
                          end: 143,
                          name: 'isBlanketHidden',
                        },
                        value: null,
                      },
                      {
                        type: 'JSXSpreadAttribute',
                        start: 144,
                        end: 152,
                        argument: {
                          type: 'CallExpression',
                          start: 148,
                          end: 151,
                          callee: {
                            type: 'Identifier',
                            start: 148,
                            end: 149,
                            name: 'x',
                          },
                          arguments: [],
                          optional: false,
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 94,
                      end: 101,
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 155,
                  end: 162,
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 162,
                  end: 186,
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 162,
                    end: 186,
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 171,
                        end: 183,
                        name: {
                          type: 'JSXIdentifier',
                          start: 171,
                          end: 175,
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 176,
                          end: 183,
                          value: 'Cahal',
                          raw: '"Cahal"',
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 163,
                      end: 170,
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 186,
                  end: 193,
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 193,
                  end: 217,
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 193,
                    end: 217,
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 202,
                        end: 214,
                        name: {
                          type: 'JSXIdentifier',
                          start: 202,
                          end: 206,
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 207,
                          end: 214,
                          value: 'Edite',
                          raw: '"Edite"',
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 194,
                      end: 201,
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 217,
                  end: 222,
                  value: '\n    ',
                  raw: '\n    ',
                },
              ],
            },
          },
        ],
      },
    },
    {
      type: 'ExpressionStatement',
      start: 237,
      end: 244,
      expression: {
        type: 'NewExpression',
        start: 237,
        end: 244,
        callee: {
          type: 'Identifier',
          start: 241,
          end: 242,
          name: 'X',
        },
        arguments: [],
      },
    },
    {
      type: 'ExpressionStatement',
      start: 246,
      end: 249,
      expression: {
        type: 'CallExpression',
        start: 246,
        end: 249,
        callee: {
          type: 'Identifier',
          start: 246,
          end: 247,
          name: 'X',
        },
        arguments: [],
        optional: false,
      },
    },
    {
      type: 'VariableDeclaration',
      start: 251,
      end: 266,
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 255,
          end: 256,
          id: {
            type: 'Identifier',
            start: 255,
            end: 256,
            name: 'z',
          },
          init: null,
        },
        {
          type: 'VariableDeclarator',
          start: 258,
          end: 260,
          id: {
            type: 'Identifier',
            start: 258,
            end: 260,
            name: 'zz',
          },
          init: null,
        },
        {
          type: 'VariableDeclarator',
          start: 262,
          end: 265,
          id: {
            type: 'Identifier',
            start: 262,
            end: 265,
            name: 'zzz',
          },
          init: null,
        },
      ],
      kind: 'let',
    },
    {
      type: 'VariableDeclaration',
      start: 267,
      end: 287,
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 273,
          end: 287,
          id: {
            type: 'Identifier',
            start: 273,
            end: 274,
            name: 'x',
          },
          init: {
            type: 'ClassExpression',
            start: 277,
            end: 287,
            id: {
              type: 'Identifier',
              start: 283,
              end: 284,
              name: 'Z',
            },
            superClass: null,
            body: {
              type: 'ClassBody',
              start: 285,
              end: 287,
              body: [],
            },
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ClassDeclaration',
      start: 289,
      end: 342,
      id: {
        type: 'Identifier',
        start: 295,
        end: 296,
        name: 'D',
      },
      superClass: {
        type: 'Identifier',
        start: 305,
        end: 306,
        name: 'B',
      },
      body: {
        type: 'ClassBody',
        start: 307,
        end: 342,
        body: [
          {
            type: 'MethodDefinition',
            start: 311,
            end: 340,
            static: false,
            computed: false,
            key: {
              type: 'Identifier',
              start: 311,
              end: 322,
              name: 'constructor',
            },
            kind: 'constructor',
            value: {
              type: 'FunctionExpression',
              start: 322,
              end: 340,
              id: null,
              expression: false,
              generator: false,
              async: false,
              params: [],
              body: {
                type: 'BlockStatement',
                start: 325,
                end: 340,
                body: [
                  {
                    type: 'ExpressionStatement',
                    start: 329,
                    end: 336,
                    expression: {
                      type: 'CallExpression',
                      start: 329,
                      end: 336,
                      callee: {
                        type: 'Super',
                        start: 329,
                        end: 334,
                      },
                      arguments: [],
                      optional: false,
                    },
                  },
                ],
              },
            },
          },
        ],
      },
    },
    {
      type: 'SwitchStatement',
      start: 344,
      end: 377,
      discriminant: {
        type: 'Identifier',
        start: 352,
        end: 353,
        name: 'e',
      },
      cases: [
        {
          type: 'SwitchCase',
          start: 359,
          end: 375,
          consequent: [
            {
              type: 'ExpressionStatement',
              start: 369,
              end: 375,
              expression: {
                type: 'Literal',
                start: 369,
                end: 374,
                value: false,
                raw: 'false',
              },
            },
          ],
          test: {
            type: 'Literal',
            start: 364,
            end: 367,
            value: 'x',
            raw: "'x'",
          },
        },
      ],
    },
    {
      type: 'EmptyStatement',
      start: 379,
      end: 380,
    },
    {
      type: 'ExpressionStatement',
      start: 380,
      end: 382,
      expression: {
        type: 'ArrayExpression',
        start: 380,
        end: 382,
        elements: [],
      },
    },
    {
      type: 'VariableDeclaration',
      start: 384,
      end: 397,
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 390,
          end: 397,
          id: {
            type: 'Identifier',
            start: 390,
            end: 392,
            name: 'yy',
          },
          init: {
            type: 'ObjectExpression',
            start: 395,
            end: 397,
            properties: [],
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'VariableDeclaration',
      start: 399,
      end: 461,
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 405,
          end: 461,
          id: {
            type: 'Identifier',
            start: 405,
            end: 406,
            name: 'y',
          },
          init: {
            type: 'JSXElement',
            start: 409,
            end: 461,
            openingElement: {
              type: 'JSXOpeningElement',
              start: 409,
              end: 448,
              attributes: [
                {
                  type: 'JSXAttribute',
                  start: 416,
                  end: 429,
                  name: {
                    type: 'JSXIdentifier',
                    start: 416,
                    end: 422,
                    name: 'isOpen',
                  },
                  value: {
                    type: 'JSXExpressionContainer',
                    start: 423,
                    end: 429,
                    expression: {
                      type: 'Literal',
                      start: 424,
                      end: 428,
                      value: true,
                      raw: 'true',
                    },
                  },
                },
                {
                  type: 'JSXAttribute',
                  start: 430,
                  end: 447,
                  name: {
                    type: 'JSXIdentifier',
                    start: 430,
                    end: 437,
                    name: 'onClick',
                  },
                  value: {
                    type: 'JSXExpressionContainer',
                    start: 438,
                    end: 447,
                    expression: {
                      type: 'Identifier',
                      start: 439,
                      end: 446,
                      name: 'onClick',
                    },
                  },
                },
              ],
              name: {
                type: 'JSXIdentifier',
                start: 410,
                end: 415,
                name: 'Modal',
              },
              selfClosing: false,
            },
            closingElement: {
              type: 'JSXClosingElement',
              start: 453,
              end: 461,
              name: {
                type: 'JSXIdentifier',
                start: 455,
                end: 460,
                name: 'Modal',
              },
            },
            children: [
              {
                type: 'JSXText',
                start: 448,
                end: 453,
                value: 'hello',
                raw: 'hello',
              },
            ],
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ExpressionStatement',
      start: 463,
      end: 527,
      expression: {
        type: 'CallExpression',
        start: 463,
        end: 526,
        callee: {
          type: 'MemberExpression',
          start: 463,
          end: 478,
          object: {
            type: 'Identifier',
            start: 463,
            end: 471,
            name: 'ReactDOM',
          },
          property: {
            type: 'Identifier',
            start: 472,
            end: 478,
            name: 'render',
          },
          computed: false,
          optional: false,
        },
        arguments: [
          {
            type: 'JSXElement',
            start: 482,
            end: 489,
            openingElement: {
              type: 'JSXOpeningElement',
              start: 482,
              end: 489,
              attributes: [],
              name: {
                type: 'JSXIdentifier',
                start: 483,
                end: 486,
                name: 'App',
              },
              selfClosing: true,
            },
            closingElement: null,
            children: [],
          },
          {
            type: 'CallExpression',
            start: 493,
            end: 524,
            callee: {
              type: 'MemberExpression',
              start: 493,
              end: 516,
              object: {
                type: 'Identifier',
                start: 493,
                end: 501,
                name: 'document',
              },
              property: {
                type: 'Identifier',
                start: 502,
                end: 516,
                name: 'getElementById',
              },
              computed: false,
              optional: false,
            },
            arguments: [
              {
                type: 'Literal',
                start: 517,
                end: 523,
                value: 'root',
                raw: "'root'",
              },
            ],
            optional: false,
          },
        ],
        optional: false,
      },
    },
  ],
  sourceType: 'module',
}
