export default {
  type: 'Program',
  start: 0,
  end: 492,
  body: [
    {
      type: 'ImportDeclaration',
      start: 0,
      end: 47,
      specifiers: [
        {
          type: 'ImportDefaultSpecifier',
          start: 7,
          end: 8,
          local: {
            type: 'Identifier',
            start: 7,
            end: 8,
            name: 'A',
          },
        },
        {
          type: 'ImportSpecifier',
          start: 12,
          end: 19,
          imported: {
            type: 'Identifier',
            start: 12,
            end: 19,
            name: 'Welcome',
          },
          local: {
            type: 'Identifier',
            start: 12,
            end: 19,
            name: 'Welcome',
          },
        },
      ],
      source: {
        type: 'Literal',
        start: 27,
        end: 46,
        value: '@atlaskit/welcome',
        raw: "'@atlaskit/welcome'",
      },
    },
    {
      type: 'FunctionDeclaration',
      start: 49,
      end: 235,
      id: {
        type: 'Identifier',
        start: 58,
        end: 61,
        name: 'App',
      },
      expression: false,
      generator: false,
      async: false,
      params: [],
      body: {
        type: 'BlockStatement',
        start: 64,
        end: 235,
        body: [
          {
            type: 'ReturnStatement',
            start: 68,
            end: 233,
            argument: {
              type: 'JSXElement',
              start: 81,
              end: 228,
              openingElement: {
                type: 'JSXOpeningElement',
                start: 81,
                end: 86,
                attributes: [],
                name: {
                  type: 'JSXIdentifier',
                  start: 82,
                  end: 85,
                  name: 'div',
                },
                selfClosing: false,
              },
              closingElement: {
                type: 'JSXClosingElement',
                start: 222,
                end: 228,
                name: {
                  type: 'JSXIdentifier',
                  start: 224,
                  end: 227,
                  name: 'div',
                },
              },
              children: [
                {
                  type: 'JSXText',
                  start: 86,
                  end: 93,
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 93,
                  end: 155,
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 93,
                    end: 155,
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 102,
                        end: 113,
                        name: {
                          type: 'JSXIdentifier',
                          start: 102,
                          end: 106,
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 107,
                          end: 113,
                          value: 'Sara',
                          raw: '"Sara"',
                        },
                      },
                      {
                        type: 'JSXAttribute',
                        start: 114,
                        end: 127,
                        name: {
                          type: 'JSXIdentifier',
                          start: 114,
                          end: 123,
                          name: 'otherName',
                        },
                        value: {
                          type: 'JSXExpressionContainer',
                          start: 124,
                          end: 127,
                          expression: {
                            type: 'Literal',
                            start: 125,
                            end: 126,
                            value: 2,
                            raw: '2',
                          },
                        },
                      },
                      {
                        type: 'JSXAttribute',
                        start: 128,
                        end: 143,
                        name: {
                          type: 'JSXIdentifier',
                          start: 128,
                          end: 143,
                          name: 'isBlanketHidden',
                        },
                        value: null,
                      },
                      {
                        type: 'JSXSpreadAttribute',
                        start: 144,
                        end: 152,
                        argument: {
                          type: 'CallExpression',
                          start: 148,
                          end: 151,
                          callee: {
                            type: 'Identifier',
                            start: 148,
                            end: 149,
                            name: 'x',
                          },
                          arguments: [],
                          optional: false,
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 94,
                      end: 101,
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 155,
                  end: 162,
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 162,
                  end: 186,
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 162,
                    end: 186,
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 171,
                        end: 183,
                        name: {
                          type: 'JSXIdentifier',
                          start: 171,
                          end: 175,
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 176,
                          end: 183,
                          value: 'Cahal',
                          raw: '"Cahal"',
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 163,
                      end: 170,
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 186,
                  end: 193,
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 193,
                  end: 217,
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 193,
                    end: 217,
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 202,
                        end: 214,
                        name: {
                          type: 'JSXIdentifier',
                          start: 202,
                          end: 206,
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 207,
                          end: 214,
                          value: 'Edite',
                          raw: '"Edite"',
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 194,
                      end: 201,
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 217,
                  end: 222,
                  value: '\n    ',
                  raw: '\n    ',
                },
              ],
            },
          },
        ],
      },
    },
    {
      type: 'ExpressionStatement',
      start: 237,
      end: 244,
      expression: {
        type: 'NewExpression',
        start: 237,
        end: 244,
        callee: {
          type: 'Identifier',
          start: 241,
          end: 242,
          name: 'X',
        },
        arguments: [],
      },
    },
    {
      type: 'ExpressionStatement',
      start: 246,
      end: 249,
      expression: {
        type: 'CallExpression',
        start: 246,
        end: 249,
        callee: {
          type: 'Identifier',
          start: 246,
          end: 247,
          name: 'X',
        },
        arguments: [],
        optional: false,
      },
    },
    {
      type: 'VariableDeclaration',
      start: 251,
      end: 271,
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 257,
          end: 271,
          id: {
            type: 'Identifier',
            start: 257,
            end: 258,
            name: 'x',
          },
          init: {
            type: 'ClassExpression',
            start: 261,
            end: 271,
            id: {
              type: 'Identifier',
              start: 267,
              end: 268,
              name: 'Z',
            },
            superClass: null,
            body: {
              type: 'ClassBody',
              start: 269,
              end: 271,
              body: [],
            },
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ClassDeclaration',
      start: 273,
      end: 326,
      id: {
        type: 'Identifier',
        start: 279,
        end: 280,
        name: 'D',
      },
      superClass: {
        type: 'Identifier',
        start: 289,
        end: 290,
        name: 'B',
      },
      body: {
        type: 'ClassBody',
        start: 291,
        end: 326,
        body: [
          {
            type: 'MethodDefinition',
            start: 295,
            end: 324,
            static: false,
            computed: false,
            key: {
              type: 'Identifier',
              start: 295,
              end: 306,
              name: 'constructor',
            },
            kind: 'constructor',
            value: {
              type: 'FunctionExpression',
              start: 306,
              end: 324,
              id: null,
              expression: false,
              generator: false,
              async: false,
              params: [],
              body: {
                type: 'BlockStatement',
                start: 309,
                end: 324,
                body: [
                  {
                    type: 'ExpressionStatement',
                    start: 313,
                    end: 320,
                    expression: {
                      type: 'CallExpression',
                      start: 313,
                      end: 320,
                      callee: {
                        type: 'Super',
                        start: 313,
                        end: 318,
                      },
                      arguments: [],
                      optional: false,
                    },
                  },
                ],
              },
            },
          },
        ],
      },
    },
    {
      type: 'SwitchStatement',
      start: 328,
      end: 361,
      discriminant: {
        type: 'Identifier',
        start: 336,
        end: 337,
        name: 'e',
      },
      cases: [
        {
          type: 'SwitchCase',
          start: 343,
          end: 359,
          consequent: [
            {
              type: 'ExpressionStatement',
              start: 353,
              end: 359,
              expression: {
                type: 'Literal',
                start: 353,
                end: 358,
                value: false,
                raw: 'false',
              },
            },
          ],
          test: {
            type: 'Literal',
            start: 348,
            end: 351,
            value: 'x',
            raw: "'x'",
          },
        },
      ],
    },
    {
      type: 'VariableDeclaration',
      start: 364,
      end: 426,
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 370,
          end: 426,
          id: {
            type: 'Identifier',
            start: 370,
            end: 371,
            name: 'y',
          },
          init: {
            type: 'JSXElement',
            start: 374,
            end: 426,
            openingElement: {
              type: 'JSXOpeningElement',
              start: 374,
              end: 413,
              attributes: [
                {
                  type: 'JSXAttribute',
                  start: 381,
                  end: 394,
                  name: {
                    type: 'JSXIdentifier',
                    start: 381,
                    end: 387,
                    name: 'isOpen',
                  },
                  value: {
                    type: 'JSXExpressionContainer',
                    start: 388,
                    end: 394,
                    expression: {
                      type: 'Literal',
                      start: 389,
                      end: 393,
                      value: true,
                      raw: 'true',
                    },
                  },
                },
                {
                  type: 'JSXAttribute',
                  start: 395,
                  end: 412,
                  name: {
                    type: 'JSXIdentifier',
                    start: 395,
                    end: 402,
                    name: 'onClick',
                  },
                  value: {
                    type: 'JSXExpressionContainer',
                    start: 403,
                    end: 412,
                    expression: {
                      type: 'Identifier',
                      start: 404,
                      end: 411,
                      name: 'onClick',
                    },
                  },
                },
              ],
              name: {
                type: 'JSXIdentifier',
                start: 375,
                end: 380,
                name: 'Modal',
              },
              selfClosing: false,
            },
            closingElement: {
              type: 'JSXClosingElement',
              start: 418,
              end: 426,
              name: {
                type: 'JSXIdentifier',
                start: 420,
                end: 425,
                name: 'Modal',
              },
            },
            children: [
              {
                type: 'JSXText',
                start: 413,
                end: 418,
                value: 'hello',
                raw: 'hello',
              },
            ],
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ExpressionStatement',
      start: 428,
      end: 492,
      expression: {
        type: 'CallExpression',
        start: 428,
        end: 491,
        callee: {
          type: 'MemberExpression',
          start: 428,
          end: 443,
          object: {
            type: 'Identifier',
            start: 428,
            end: 436,
            name: 'ReactDOM',
          },
          property: {
            type: 'Identifier',
            start: 437,
            end: 443,
            name: 'render',
          },
          computed: false,
          optional: false,
        },
        arguments: [
          {
            type: 'JSXElement',
            start: 447,
            end: 454,
            openingElement: {
              type: 'JSXOpeningElement',
              start: 447,
              end: 454,
              attributes: [],
              name: {
                type: 'JSXIdentifier',
                start: 448,
                end: 451,
                name: 'App',
              },
              selfClosing: true,
            },
            closingElement: null,
            children: [],
          },
          {
            type: 'CallExpression',
            start: 458,
            end: 489,
            callee: {
              type: 'MemberExpression',
              start: 458,
              end: 481,
              object: {
                type: 'Identifier',
                start: 458,
                end: 466,
                name: 'document',
              },
              property: {
                type: 'Identifier',
                start: 467,
                end: 481,
                name: 'getElementById',
              },
              computed: false,
              optional: false,
            },
            arguments: [
              {
                type: 'Literal',
                start: 482,
                end: 488,
                value: 'root',
                raw: "'root'",
              },
            ],
            optional: false,
          },
        ],
        optional: false,
      },
    },
  ],
  sourceType: 'module',
}
