export default {
  type: 'Program',
  start: 0,
  end: 1128,
  range: [0, 1127],
  body: [
    {
      type: 'ImportDeclaration',
      start: 0,
      end: 47,
      range: [0, 47],
      specifiers: [
        {
          type: 'ImportDefaultSpecifier',
          start: 7,
          end: 8,
          range: [7, 8],
          local: {
            type: 'Identifier',
            start: 7,
            end: 8,
            range: [7, 8],
            name: 'A',
          },
        },
        {
          type: 'ImportSpecifier',
          start: 12,
          end: 19,
          range: [12, 19],
          imported: {
            type: 'Identifier',
            start: 12,
            end: 19,
            range: [12, 19],
            name: 'Welcome',
          },
          local: {
            type: 'Identifier',
            start: 12,
            end: 19,
            range: [12, 19],
            name: 'Welcome',
          },
        },
      ],
      source: {
        type: 'Literal',
        start: 27,
        end: 46,
        range: [27, 46],
        value: '@atlaskit/welcome',
        raw: "'@atlaskit/welcome'",
      },
    },
    {
      type: 'ImportDeclaration',
      start: 48,
      end: 75,
      range: [48, 75],
      specifiers: [
        {
          type: 'ImportSpecifier',
          start: 57,
          end: 58,
          range: [57, 58],
          imported: {
            type: 'Identifier',
            start: 57,
            end: 58,
            range: [57, 58],
            name: 'X',
          },
          local: {
            type: 'Identifier',
            start: 57,
            end: 58,
            range: [57, 58],
            name: 'X',
          },
        },
      ],
      source: {
        type: 'Literal',
        start: 66,
        end: 75,
        range: [66, 75],
        value: './other',
        raw: "'./other'",
      },
    },
    {
      type: 'ImportDeclaration',
      start: 76,
      end: 107,
      range: [76, 107],
      specifiers: [
        {
          type: 'ImportDefaultSpecifier',
          start: 83,
          end: 86,
          range: [83, 86],
          local: {
            type: 'Identifier',
            start: 83,
            end: 86,
            range: [83, 86],
            name: 'tmm',
          },
        },
        {
          type: 'ImportNamespaceSpecifier',
          start: 88,
          end: 94,
          range: [88, 94],
          local: {
            type: 'Identifier',
            start: 93,
            end: 94,
            range: [93, 94],
            name: 'x',
          },
        },
      ],
      source: {
        type: 'Literal',
        start: 100,
        end: 107,
        range: [100, 107],
        value: 'thing',
        raw: "'thing'",
      },
    },
    {
      type: 'ImportDeclaration',
      start: 108,
      end: 121,
      range: [108, 121],
      specifiers: [],
      source: {
        type: 'Literal',
        start: 115,
        end: 121,
        range: [115, 121],
        value: 'blah',
        raw: "'blah'",
      },
    },
    {
      type: 'FunctionDeclaration',
      start: 123,
      end: 324,
      range: [123, 324],
      id: {
        type: 'Identifier',
        start: 132,
        end: 135,
        range: [132, 135],
        name: 'App',
      },
      expression: false,
      generator: false,
      async: false,
      params: [
        {
          type: 'ObjectPattern',
          start: 136,
          end: 141,
          range: [136, 141],
          properties: [
            {
              type: 'Property',
              start: 138,
              end: 139,
              range: [138, 139],
              method: false,
              shorthand: true,
              computed: false,
              key: {
                type: 'Identifier',
                start: 138,
                end: 139,
                range: [138, 139],
                name: 'a',
              },
              kind: 'init',
              value: {
                type: 'Identifier',
                start: 138,
                end: 139,
                range: [138, 139],
                name: 'a',
              },
            },
          ],
        },
        {
          type: 'ObjectPattern',
          start: 143,
          end: 151,
          range: [143, 151],
          properties: [
            {
              type: 'Property',
              start: 145,
              end: 149,
              range: [145, 149],
              method: false,
              shorthand: false,
              computed: false,
              key: {
                type: 'Identifier',
                start: 145,
                end: 146,
                range: [145, 146],
                name: 'b',
              },
              value: {
                type: 'Identifier',
                start: 148,
                end: 149,
                range: [148, 149],
                name: 'c',
              },
              kind: 'init',
            },
          ],
        },
      ],
      body: {
        type: 'BlockStatement',
        start: 153,
        end: 324,
        range: [153, 324],
        body: [
          {
            type: 'ReturnStatement',
            start: 157,
            end: 322,
            range: [157, 322],
            argument: {
              type: 'JSXElement',
              start: 170,
              end: 317,
              range: [170, 317],
              openingElement: {
                type: 'JSXOpeningElement',
                start: 170,
                end: 175,
                range: [170, 175],
                attributes: [],
                name: {
                  type: 'JSXIdentifier',
                  start: 171,
                  end: 174,
                  range: [171, 174],
                  name: 'div',
                },
                selfClosing: false,
              },
              closingElement: {
                type: 'JSXClosingElement',
                start: 311,
                end: 317,
                range: [311, 317],
                name: {
                  type: 'JSXIdentifier',
                  start: 313,
                  end: 316,
                  range: [313, 316],
                  name: 'div',
                },
              },
              children: [
                {
                  type: 'JSXText',
                  start: 175,
                  end: 182,
                  range: [175, 182],
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 182,
                  end: 244,
                  range: [182, 244],
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 182,
                    end: 244,
                    range: [182, 244],
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 191,
                        end: 202,
                        range: [191, 202],
                        name: {
                          type: 'JSXIdentifier',
                          start: 191,
                          end: 195,
                          range: [191, 195],
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 196,
                          end: 202,
                          range: [196, 202],
                          value: 'Sara',
                          raw: '"Sara"',
                        },
                      },
                      {
                        type: 'JSXAttribute',
                        start: 203,
                        end: 216,
                        range: [203, 216],
                        name: {
                          type: 'JSXIdentifier',
                          start: 203,
                          end: 212,
                          range: [203, 212],
                          name: 'otherName',
                        },
                        value: {
                          type: 'JSXExpressionContainer',
                          start: 213,
                          end: 216,
                          range: [213, 216],
                          expression: {
                            type: 'Literal',
                            start: 214,
                            end: 215,
                            range: [214, 215],
                            value: 2,
                            raw: '2',
                          },
                        },
                      },
                      {
                        type: 'JSXAttribute',
                        start: 217,
                        end: 232,
                        range: [217, 232],
                        name: {
                          type: 'JSXIdentifier',
                          start: 217,
                          end: 232,
                          range: [217, 232],
                          name: 'isBlanketHidden',
                        },
                        value: null,
                      },
                      {
                        type: 'JSXSpreadAttribute',
                        start: 233,
                        end: 241,
                        range: [233, 241],
                        argument: {
                          type: 'CallExpression',
                          start: 237,
                          end: 240,
                          range: [237, 240],
                          callee: {
                            type: 'Identifier',
                            start: 237,
                            end: 238,
                            range: [237, 238],
                            name: 'x',
                          },
                          arguments: [],
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 183,
                      end: 190,
                      range: [183, 190],
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 244,
                  end: 251,
                  range: [244, 251],
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 251,
                  end: 275,
                  range: [251, 275],
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 251,
                    end: 275,
                    range: [251, 275],
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 260,
                        end: 272,
                        range: [260, 272],
                        name: {
                          type: 'JSXIdentifier',
                          start: 260,
                          end: 264,
                          range: [260, 264],
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 265,
                          end: 272,
                          range: [265, 272],
                          value: 'Cahal',
                          raw: '"Cahal"',
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 252,
                      end: 259,
                      range: [252, 259],
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 275,
                  end: 282,
                  range: [275, 282],
                  value: '\n      ',
                  raw: '\n      ',
                },
                {
                  type: 'JSXElement',
                  start: 282,
                  end: 306,
                  range: [282, 306],
                  openingElement: {
                    type: 'JSXOpeningElement',
                    start: 282,
                    end: 306,
                    range: [282, 306],
                    attributes: [
                      {
                        type: 'JSXAttribute',
                        start: 291,
                        end: 303,
                        range: [291, 303],
                        name: {
                          type: 'JSXIdentifier',
                          start: 291,
                          end: 295,
                          range: [291, 295],
                          name: 'name',
                        },
                        value: {
                          type: 'Literal',
                          start: 296,
                          end: 303,
                          range: [296, 303],
                          value: 'Edite',
                          raw: '"Edite"',
                        },
                      },
                    ],
                    name: {
                      type: 'JSXIdentifier',
                      start: 283,
                      end: 290,
                      range: [283, 290],
                      name: 'Welcome',
                    },
                    selfClosing: true,
                  },
                  closingElement: null,
                  children: [],
                },
                {
                  type: 'JSXText',
                  start: 306,
                  end: 311,
                  range: [306, 311],
                  value: '\n    ',
                  raw: '\n    ',
                },
              ],
            },
          },
        ],
      },
    },
    {
      type: 'VariableDeclaration',
      start: 326,
      end: 347,
      range: [326, 347],
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 332,
          end: 347,
          range: [332, 347],
          id: {
            type: 'Identifier',
            start: 332,
            end: 337,
            range: [332, 337],
            name: 'silly',
          },
          init: {
            type: 'SequenceExpression',
            start: 341,
            end: 346,
            range: [341, 346],
            expressions: [
              {
                type: 'Literal',
                start: 341,
                end: 342,
                range: [341, 342],
                value: 1,
                raw: '1',
              },
              {
                type: 'Literal',
                start: 345,
                end: 346,
                range: [345, 346],
                value: 3,
                raw: '3',
              },
            ],
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ExpressionStatement',
      start: 358,
      end: 414,
      range: [358, 414],
      expression: {
        type: 'NewExpression',
        start: 358,
        end: 414,
        range: [358, 414],
        callee: {
          type: 'Identifier',
          start: 362,
          end: 363,
          range: [362, 363],
          name: 'X',
        },
        arguments: [
          {
            type: 'TemplateLiteral',
            start: 364,
            end: 413,
            range: [364, 413],
            expressions: [
              {
                type: 'Identifier',
                start: 367,
                end: 372,
                range: [367, 372],
                name: 'hello',
              },
              {
                type: 'ConditionalExpression',
                start: 385,
                end: 411,
                range: [385, 411],
                test: {
                  type: 'BinaryExpression',
                  start: 385,
                  end: 391,
                  range: [385, 391],
                  left: {
                    type: 'Literal',
                    start: 385,
                    end: 386,
                    range: [385, 386],
                    value: 1,
                    raw: '1',
                  },
                  operator: '==',
                  right: {
                    type: 'Literal',
                    start: 390,
                    end: 391,
                    range: [390, 391],
                    value: 2,
                    raw: '2',
                  },
                },
                consequent: {
                  type: 'TemplateLiteral',
                  start: 394,
                  end: 406,
                  range: [394, 406],
                  expressions: [
                    {
                      type: 'Identifier',
                      start: 397,
                      end: 404,
                      range: [397, 404],
                      name: 'Welcome',
                    },
                  ],
                  quasis: [
                    {
                      type: 'TemplateElement',
                      start: 395,
                      end: 395,
                      range: [394, 397],
                      value: {
                        raw: '',
                        cooked: '',
                      },
                      tail: false,
                    },
                    {
                      type: 'TemplateElement',
                      start: 405,
                      end: 405,
                      range: [404, 406],
                      value: {
                        raw: '',
                        cooked: '',
                      },
                      tail: true,
                    },
                  ],
                },
                alternate: {
                  type: 'Literal',
                  start: 409,
                  end: 411,
                  range: [409, 411],
                  value: '',
                  raw: "''",
                },
              },
            ],
            quasis: [
              {
                type: 'TemplateElement',
                start: 365,
                end: 365,
                range: [364, 367],
                value: {
                  raw: '',
                  cooked: '',
                },
                tail: false,
              },
              {
                type: 'TemplateElement',
                start: 373,
                end: 383,
                range: [372, 385],
                value: {
                  raw: ': "world" ',
                  cooked: ': "world" ',
                },
                tail: false,
              },
              {
                type: 'TemplateElement',
                start: 412,
                end: 412,
                range: [411, 413],
                value: {
                  raw: '',
                  cooked: '',
                },
                tail: true,
              },
            ],
          },
        ],
      },
    },
    {
      type: 'ExpressionStatement',
      start: 416,
      end: 419,
      range: [416, 419],
      expression: {
        type: 'CallExpression',
        start: 416,
        end: 419,
        range: [416, 419],
        callee: {
          type: 'Identifier',
          start: 416,
          end: 417,
          range: [416, 417],
          name: 'X',
        },
        arguments: [],
      },
    },
    {
      type: 'VariableDeclaration',
      start: 421,
      end: 436,
      range: [421, 436],
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 425,
          end: 426,
          range: [425, 426],
          id: {
            type: 'Identifier',
            start: 425,
            end: 426,
            range: [425, 426],
            name: 'z',
          },
          init: null,
        },
        {
          type: 'VariableDeclarator',
          start: 428,
          end: 430,
          range: [428, 430],
          id: {
            type: 'Identifier',
            start: 428,
            end: 430,
            range: [428, 430],
            name: 'zz',
          },
          init: null,
        },
        {
          type: 'VariableDeclarator',
          start: 432,
          end: 435,
          range: [432, 435],
          id: {
            type: 'Identifier',
            start: 432,
            end: 435,
            range: [432, 435],
            name: 'zzz',
          },
          init: null,
        },
      ],
      kind: 'let',
    },
    {
      type: 'VariableDeclaration',
      start: 437,
      end: 457,
      range: [437, 457],
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 443,
          end: 457,
          range: [443, 457],
          id: {
            type: 'Identifier',
            start: 443,
            end: 444,
            range: [443, 444],
            name: 'p',
          },
          init: {
            type: 'ClassExpression',
            start: 447,
            end: 457,
            range: [447, 457],
            id: {
              type: 'Identifier',
              start: 453,
              end: 454,
              range: [453, 454],
              name: 'Z',
            },
            superClass: null,
            body: {
              type: 'ClassBody',
              start: 455,
              end: 457,
              range: [455, 457],
              body: [],
            },
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ClassDeclaration',
      start: 459,
      end: 577,
      range: [459, 577],
      id: {
        type: 'Identifier',
        start: 465,
        end: 466,
        range: [465, 466],
        name: 'D',
      },
      superClass: {
        type: 'Identifier',
        start: 475,
        end: 476,
        range: [475, 476],
        name: 'B',
      },
      body: {
        type: 'ClassBody',
        start: 477,
        end: 577,
        range: [477, 577],
        body: [
          {
            type: 'MethodDefinition',
            start: 482,
            end: 535,
            range: [482, 535],
            kind: 'constructor',
            static: false,
            computed: false,
            key: {
              type: 'Identifier',
              start: 482,
              end: 493,
              range: [482, 493],
              name: 'constructor',
            },
            value: {
              type: 'FunctionExpression',
              start: 493,
              end: 535,
              range: [493, 535],
              id: null,
              expression: false,
              generator: false,
              async: false,
              params: [],
              body: {
                type: 'BlockStatement',
                start: 496,
                end: 535,
                range: [496, 535],
                body: [
                  {
                    type: 'ExpressionStatement',
                    start: 500,
                    end: 508,
                    range: [500, 508],
                    expression: {
                      type: 'CallExpression',
                      start: 500,
                      end: 507,
                      range: [500, 507],
                      callee: {
                        type: 'Super',
                        start: 500,
                        end: 505,
                        range: [500, 505],
                      },
                      arguments: [],
                    },
                  },
                  {
                    type: 'ExpressionStatement',
                    start: 513,
                    end: 531,
                    range: [513, 531],
                    expression: {
                      type: 'AssignmentExpression',
                      start: 513,
                      end: 530,
                      range: [513, 530],
                      operator: '=',
                      left: {
                        type: 'MemberExpression',
                        start: 513,
                        end: 523,
                        range: [513, 523],
                        object: {
                          type: 'ThisExpression',
                          start: 513,
                          end: 517,
                          range: [513, 517],
                        },
                        property: {
                          type: 'Identifier',
                          start: 518,
                          end: 523,
                          range: [518, 523],
                          name: 'hello',
                        },
                        computed: false,
                      },
                      right: {
                        type: 'Literal',
                        start: 526,
                        end: 530,
                        range: [526, 530],
                        value: 'hi',
                        raw: "'hi'",
                      },
                    },
                  },
                ],
              },
            },
          },
          {
            type: 'MethodDefinition',
            start: 539,
            end: 575,
            range: [539, 575],
            kind: 'method',
            static: false,
            computed: false,
            key: {
              type: 'Identifier',
              start: 539,
              end: 544,
              range: [539, 544],
              name: 'other',
            },
            value: {
              type: 'FunctionExpression',
              start: 544,
              end: 575,
              range: [544, 575],
              id: null,
              expression: false,
              generator: false,
              async: false,
              params: [],
              body: {
                type: 'BlockStatement',
                start: 547,
                end: 575,
                range: [547, 575],
                body: [
                  {
                    type: 'ReturnStatement',
                    start: 553,
                    end: 571,
                    range: [553, 571],
                    argument: {
                      type: 'MemberExpression',
                      start: 560,
                      end: 570,
                      range: [560, 570],
                      object: {
                        type: 'ThisExpression',
                        start: 560,
                        end: 564,
                        range: [560, 564],
                      },
                      property: {
                        type: 'Identifier',
                        start: 565,
                        end: 570,
                        range: [565, 570],
                        name: 'hello',
                      },
                      computed: false,
                    },
                  },
                ],
              },
            },
          },
        ],
      },
    },
    {
      type: 'SwitchStatement',
      start: 579,
      end: 633,
      range: [579, 633],
      discriminant: {
        type: 'Identifier',
        start: 587,
        end: 588,
        range: [587, 588],
        name: 'e',
      },
      cases: [
        {
          type: 'SwitchCase',
          start: 594,
          end: 614,
          range: [594, 614],
          consequent: [
            {
              type: 'ExpressionStatement',
              start: 604,
              end: 610,
              range: [604, 610],
              expression: {
                type: 'Literal',
                start: 604,
                end: 609,
                range: [604, 609],
                value: false,
                raw: 'false',
              },
            },
            {
              type: 'ExpressionStatement',
              start: 611,
              end: 614,
              range: [611, 614],
              expression: {
                type: 'Literal',
                start: 611,
                end: 613,
                range: [611, 613],
                value: '',
                raw: "''",
              },
            },
          ],
          test: {
            type: 'Literal',
            start: 599,
            end: 602,
            range: [599, 602],
            value: 'x',
            raw: "'x'",
          },
        },
        {
          type: 'SwitchCase',
          start: 617,
          end: 631,
          range: [617, 631],
          consequent: [
            {
              type: 'ExpressionStatement',
              start: 626,
              end: 631,
              range: [626, 631],
              expression: {
                type: 'Literal',
                start: 626,
                end: 630,
                range: [626, 630],
                value: 'zz',
                raw: "'zz'",
              },
            },
          ],
          test: null,
        },
      ],
    },
    {
      type: 'VariableDeclaration',
      start: 635,
      end: 655,
      range: [635, 655],
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 641,
          end: 655,
          range: [641, 655],
          id: {
            type: 'Identifier',
            start: 641,
            end: 643,
            range: [641, 643],
            name: 'v1',
          },
          init: {
            type: 'BinaryExpression',
            start: 646,
            end: 655,
            range: [646, 655],
            left: {
              type: 'BinaryExpression',
              start: 646,
              end: 651,
              range: [646, 651],
              left: {
                type: 'Literal',
                start: 646,
                end: 647,
                range: [646, 647],
                value: 1,
                raw: '1',
              },
              operator: '+',
              right: {
                type: 'Literal',
                start: 650,
                end: 651,
                range: [650, 651],
                value: 4,
                raw: '4',
              },
            },
            operator: '+',
            right: {
              type: 'Literal',
              start: 654,
              end: 655,
              range: [654, 655],
              value: 2,
              raw: '2',
            },
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'BlockStatement',
      start: 657,
      end: 672,
      range: [657, 672],
      body: [
        {
          type: 'VariableDeclaration',
          start: 660,
          end: 669,
          range: [660, 669],
          declarations: [
            {
              type: 'VariableDeclarator',
              start: 664,
              end: 669,
              range: [664, 669],
              id: {
                type: 'Identifier',
                start: 664,
                end: 665,
                range: [664, 665],
                name: 'a',
              },
              init: {
                type: 'Literal',
                start: 668,
                end: 669,
                range: [668, 669],
                value: 1,
                raw: '1',
              },
            },
          ],
          kind: 'let',
        },
      ],
    },
    {
      type: 'EmptyStatement',
      start: 674,
      end: 675,
      range: [674, 675],
    },
    {
      type: 'ExpressionStatement',
      start: 675,
      end: 677,
      range: [675, 677],
      expression: {
        type: 'ArrayExpression',
        start: 675,
        end: 677,
        range: [675, 677],
        elements: [],
      },
    },
    {
      type: 'VariableDeclaration',
      start: 679,
      end: 842,
      range: [679, 842],
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 685,
          end: 842,
          range: [685, 842],
          id: {
            type: 'Identifier',
            start: 685,
            end: 687,
            range: [685, 687],
            name: 'yy',
          },
          init: {
            type: 'ObjectExpression',
            start: 690,
            end: 842,
            range: [690, 842],
            properties: [
              {
                type: 'Property',
                start: 694,
                end: 698,
                range: [694, 698],
                method: false,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 694,
                  end: 695,
                  range: [694, 695],
                  name: 'a',
                },
                value: {
                  type: 'Literal',
                  start: 697,
                  end: 698,
                  range: [697, 698],
                  value: 1,
                  raw: '1',
                },
                kind: 'init',
              },
              {
                type: 'Property',
                start: 702,
                end: 712,
                range: [702, 712],
                method: false,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 706,
                  end: 707,
                  range: [706, 707],
                  name: 'z',
                },
                kind: 'get',
                value: {
                  type: 'FunctionExpression',
                  start: 707,
                  end: 712,
                  range: [707, 712],
                  id: null,
                  expression: false,
                  generator: false,
                  async: false,
                  params: [],
                  body: {
                    type: 'BlockStatement',
                    start: 710,
                    end: 712,
                    range: [710, 712],
                    body: [],
                  },
                },
              },
              {
                type: 'Property',
                start: 716,
                end: 727,
                range: [716, 727],
                method: false,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 720,
                  end: 721,
                  range: [720, 721],
                  name: 'j',
                },
                kind: 'set',
                value: {
                  type: 'FunctionExpression',
                  start: 721,
                  end: 727,
                  range: [721, 727],
                  id: null,
                  expression: false,
                  generator: false,
                  async: false,
                  params: [
                    {
                      type: 'Identifier',
                      start: 722,
                      end: 723,
                      range: [722, 723],
                      name: 'j',
                    },
                  ],
                  body: {
                    type: 'BlockStatement',
                    start: 725,
                    end: 727,
                    range: [725, 727],
                    body: [],
                  },
                },
              },
              {
                type: 'Property',
                start: 731,
                end: 740,
                range: [731, 740],
                method: true,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 731,
                  end: 735,
                  range: [731, 735],
                  name: 'init',
                },
                kind: 'init',
                value: {
                  type: 'FunctionExpression',
                  start: 735,
                  end: 740,
                  range: [735, 740],
                  id: null,
                  expression: false,
                  generator: false,
                  async: false,
                  params: [],
                  body: {
                    type: 'BlockStatement',
                    start: 738,
                    end: 740,
                    range: [738, 740],
                    body: [],
                  },
                },
              },
              {
                type: 'Property',
                start: 744,
                end: 759,
                range: [744, 759],
                method: true,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 750,
                  end: 754,
                  range: [750, 754],
                  name: 'blob',
                },
                kind: 'init',
                value: {
                  type: 'FunctionExpression',
                  start: 754,
                  end: 759,
                  range: [754, 759],
                  id: null,
                  expression: false,
                  generator: false,
                  async: true,
                  params: [],
                  body: {
                    type: 'BlockStatement',
                    start: 757,
                    end: 759,
                    range: [757, 759],
                    body: [],
                  },
                },
              },
              {
                type: 'Property',
                start: 763,
                end: 770,
                range: [763, 770],
                method: true,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 763,
                  end: 764,
                  range: [763, 764],
                  name: 'b',
                },
                kind: 'init',
                value: {
                  type: 'FunctionExpression',
                  start: 764,
                  end: 770,
                  range: [764, 770],
                  id: null,
                  expression: false,
                  generator: false,
                  async: false,
                  params: [],
                  body: {
                    type: 'BlockStatement',
                    start: 767,
                    end: 770,
                    range: [767, 770],
                    body: [],
                  },
                },
              },
              {
                type: 'Property',
                start: 774,
                end: 792,
                range: [774, 792],
                method: false,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 774,
                  end: 775,
                  range: [774, 775],
                  name: 'c',
                },
                value: {
                  type: 'FunctionExpression',
                  start: 777,
                  end: 792,
                  range: [777, 792],
                  id: {
                    type: 'Identifier',
                    start: 786,
                    end: 787,
                    range: [786, 787],
                    name: 'd',
                  },
                  expression: false,
                  generator: false,
                  async: false,
                  params: [],
                  body: {
                    type: 'BlockStatement',
                    start: 790,
                    end: 792,
                    range: [790, 792],
                    body: [],
                  },
                },
                kind: 'init',
              },
              {
                type: 'Property',
                start: 796,
                end: 813,
                range: [796, 813],
                method: false,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 796,
                  end: 798,
                  range: [796, 798],
                  name: 'pp',
                },
                value: {
                  type: 'FunctionExpression',
                  start: 800,
                  end: 813,
                  range: [800, 813],
                  id: null,
                  expression: false,
                  generator: false,
                  async: false,
                  params: [],
                  body: {
                    type: 'BlockStatement',
                    start: 811,
                    end: 813,
                    range: [811, 813],
                    body: [],
                  },
                },
                kind: 'init',
              },
              {
                type: 'Property',
                start: 817,
                end: 840,
                range: [817, 840],
                method: false,
                shorthand: false,
                computed: false,
                key: {
                  type: 'Identifier',
                  start: 817,
                  end: 819,
                  range: [817, 819],
                  name: 'zz',
                },
                value: {
                  type: 'FunctionExpression',
                  start: 821,
                  end: 840,
                  range: [821, 840],
                  id: null,
                  expression: false,
                  generator: false,
                  async: true,
                  params: [],
                  body: {
                    type: 'BlockStatement',
                    start: 838,
                    end: 840,
                    range: [838, 840],
                    body: [],
                  },
                },
                kind: 'init',
              },
            ],
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ForStatement',
      start: 844,
      end: 878,
      range: [844, 878],
      init: {
        type: 'VariableDeclaration',
        start: 849,
        end: 856,
        range: [849, 856],
        declarations: [
          {
            type: 'VariableDeclarator',
            start: 853,
            end: 856,
            range: [853, 856],
            id: {
              type: 'Identifier',
              start: 853,
              end: 854,
              range: [853, 854],
              name: 'i',
            },
            init: {
              type: 'Literal',
              start: 855,
              end: 856,
              range: [855, 856],
              value: 0,
              raw: '0',
            },
          },
        ],
        kind: 'let',
      },
      test: null,
      update: {
        type: 'UpdateExpression',
        start: 858,
        end: 861,
        range: [858, 861],
        operator: '++',
        prefix: false,
        argument: {
          type: 'Identifier',
          start: 858,
          end: 859,
          range: [858, 859],
          name: 'i',
        },
      },
      body: {
        type: 'BlockStatement',
        start: 863,
        end: 878,
        range: [863, 878],
        body: [
          {
            type: 'ContinueStatement',
            start: 866,
            end: 875,
            range: [866, 875],
            label: null,
          },
        ],
      },
    },
    {
      type: 'WhileStatement',
      start: 880,
      end: 906,
      range: [880, 906],
      test: {
        type: 'BinaryExpression',
        start: 887,
        end: 892,
        range: [887, 892],
        left: {
          type: 'Identifier',
          start: 887,
          end: 888,
          range: [887, 888],
          name: 'i',
        },
        operator: '<',
        right: {
          type: 'Literal',
          start: 891,
          end: 892,
          range: [891, 892],
          value: 0,
          raw: '0',
        },
      },
      body: {
        type: 'BlockStatement',
        start: 894,
        end: 906,
        range: [894, 906],
        body: [
          {
            type: 'BreakStatement',
            start: 898,
            end: 904,
            range: [898, 904],
            label: null,
          },
        ],
      },
    },
    {
      type: 'VariableDeclaration',
      start: 908,
      end: 970,
      range: [908, 970],
      declarations: [
        {
          type: 'VariableDeclarator',
          start: 914,
          end: 970,
          range: [914, 970],
          id: {
            type: 'Identifier',
            start: 914,
            end: 915,
            range: [914, 915],
            name: 'y',
          },
          init: {
            type: 'JSXElement',
            start: 918,
            end: 970,
            range: [918, 970],
            openingElement: {
              type: 'JSXOpeningElement',
              start: 918,
              end: 957,
              range: [918, 957],
              attributes: [
                {
                  type: 'JSXAttribute',
                  start: 925,
                  end: 938,
                  range: [925, 938],
                  name: {
                    type: 'JSXIdentifier',
                    start: 925,
                    end: 931,
                    range: [925, 931],
                    name: 'isOpen',
                  },
                  value: {
                    type: 'JSXExpressionContainer',
                    start: 932,
                    end: 938,
                    range: [932, 938],
                    expression: {
                      type: 'Literal',
                      start: 933,
                      end: 937,
                      range: [933, 937],
                      value: true,
                      raw: 'true',
                    },
                  },
                },
                {
                  type: 'JSXAttribute',
                  start: 939,
                  end: 956,
                  range: [939, 956],
                  name: {
                    type: 'JSXIdentifier',
                    start: 939,
                    end: 946,
                    range: [939, 946],
                    name: 'onClick',
                  },
                  value: {
                    type: 'JSXExpressionContainer',
                    start: 947,
                    end: 956,
                    range: [947, 956],
                    expression: {
                      type: 'Identifier',
                      start: 948,
                      end: 955,
                      range: [948, 955],
                      name: 'onClick',
                    },
                  },
                },
              ],
              name: {
                type: 'JSXIdentifier',
                start: 919,
                end: 924,
                range: [919, 924],
                name: 'Modal',
              },
              selfClosing: false,
            },
            closingElement: {
              type: 'JSXClosingElement',
              start: 962,
              end: 970,
              range: [962, 970],
              name: {
                type: 'JSXIdentifier',
                start: 964,
                end: 969,
                range: [964, 969],
                name: 'Modal',
              },
            },
            children: [
              {
                type: 'JSXText',
                start: 957,
                end: 962,
                range: [957, 962],
                value: 'hello',
                raw: 'hello',
              },
            ],
          },
        },
      ],
      kind: 'const',
    },
    {
      type: 'ExpressionStatement',
      start: 972,
      end: 1036,
      range: [972, 1036],
      expression: {
        type: 'CallExpression',
        start: 972,
        end: 1035,
        range: [972, 1035],
        callee: {
          type: 'MemberExpression',
          start: 972,
          end: 987,
          range: [972, 987],
          object: {
            type: 'Identifier',
            start: 972,
            end: 980,
            range: [972, 980],
            name: 'ReactDOM',
          },
          property: {
            type: 'Identifier',
            start: 981,
            end: 987,
            range: [981, 987],
            name: 'render',
          },
          computed: false,
        },
        arguments: [
          {
            type: 'JSXElement',
            start: 991,
            end: 998,
            range: [991, 998],
            openingElement: {
              type: 'JSXOpeningElement',
              start: 991,
              end: 998,
              range: [991, 998],
              attributes: [],
              name: {
                type: 'JSXIdentifier',
                start: 992,
                end: 995,
                range: [992, 995],
                name: 'App',
              },
              selfClosing: true,
            },
            closingElement: null,
            children: [],
          },
          {
            type: 'CallExpression',
            start: 1002,
            end: 1033,
            range: [1002, 1033],
            callee: {
              type: 'MemberExpression',
              start: 1002,
              end: 1025,
              range: [1002, 1025],
              object: {
                type: 'Identifier',
                start: 1002,
                end: 1010,
                range: [1002, 1010],
                name: 'document',
              },
              property: {
                type: 'Identifier',
                start: 1011,
                end: 1025,
                range: [1011, 1025],
                name: 'getElementById',
              },
              computed: false,
            },
            arguments: [
              {
                type: 'Literal',
                start: 1026,
                end: 1032,
                range: [1026, 1032],
                value: 'root',
                raw: "'root'",
              },
            ],
          },
        ],
      },
    },
    {
      type: 'ExportNamedDeclaration',
      start: 1038,
      end: 1070,
      range: [1038, 1070],
      declaration: null,
      specifiers: [
        {
          type: 'ExportSpecifier',
          start: 1047,
          end: 1053,
          range: [1047, 1053],
          local: {
            type: 'Identifier',
            start: 1047,
            end: 1048,
            range: [1047, 1048],
            name: 'y',
          },
          exported: {
            type: 'Identifier',
            start: 1052,
            end: 1053,
            range: [1052, 1053],
            name: 'b',
          },
        },
      ],
      source: {
        type: 'Literal',
        start: 1061,
        end: 1070,
        range: [1061, 1070],
        value: './other',
        raw: "'./other'",
      },
    },
    {
      type: 'ExportDefaultDeclaration',
      start: 1071,
      end: 1087,
      range: [1071, 1087],
      declaration: {
        type: 'Identifier',
        start: 1086,
        end: 1087,
        range: [1086, 1087],
        name: 'b',
      },
    },
    {
      type: 'ExportNamedDeclaration',
      start: 1088,
      end: 1109,
      range: [1088, 1109],
      declaration: {
        type: 'VariableDeclaration',
        start: 1095,
        end: 1109,
        range: [1095, 1109],
        declarations: [
          {
            type: 'VariableDeclarator',
            start: 1101,
            end: 1109,
            range: [1101, 1109],
            id: {
              type: 'Identifier',
              start: 1101,
              end: 1104,
              range: [1101, 1104],
              name: 'yyy',
            },
            init: {
              type: 'Literal',
              start: 1107,
              end: 1109,
              range: [1107, 1109],
              value: 10,
              raw: '10',
            },
          },
        ],
        kind: 'const',
      },
      specifiers: [],
      source: null,
    },
    {
      type: 'ExportAllDeclaration',
      start: 1110,
      end: 1127,
      range: [1110, 1127],
      source: {
        type: 'Literal',
        start: 1124,
        end: 1127,
        range: [1124, 1127],
        value: 's',
        raw: "'s'",
      },
    },
  ],
  sourceType: 'module',
}
